//export const dumbTableData =[]
export const dumbTableData = [
  {
    picture: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    fullname: "Archibold",
    email: "ageed@liveinternet.ru",
    role: "Project Manager",
    phoneNumber: "943-358-0519",
    address:
      "Room 486 lorem55555555555555555555555555555555555555555555555555555555555555555dddddddddddddddddddddddddddddd5",
  },
  {
    picture: "http://dummyimage.com/199x100.png/dddddd/000000",
    fullname: "Mel Peabody",
    email: "mpeabodye@geocities.com",
    role: "Estimator",
    phoneNumber: "768-199-8269",
    address: "Room 822",
  },
  {
    picture: "http://dummyimage.com/118x100.png/ff4444/ffffff",
    fullname: "Micki Tween",
    email: "mtweenf@apache.org",
    role: "Engineer",
    phoneNumber: "778-366-0165",
    address: "Suite 94",
  },
  {
    picture: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    fullname: "Archibold Delort",
    email: "adelortg@cbslocal.com",
    role: "Construction Manager",
    phoneNumber: "842-864-0585",
    address: "17th Floor",
  },
  {
    picture: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    fullname: "Chandra Ciccone",
    email: "ccicconeh@blogs.com",
    role: "Construction Worker",
    phoneNumber: "706-958-0548",
    address: "6th Floor",
  },
  {
    picture: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    fullname: "Hilary Kesten",
    email: "hkesteni@freewebs.com",
    role: "Project Manager",
    phoneNumber: "637-716-9596",
    address: "PO Box 46890",
  },
  {
    picture: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    fullname: "Dani Adolf",
    email: "dadolfj@columbia.edu",
    role: "Estimator",
    phoneNumber: "196-923-9672",
    address: "Room 291",
  },
  {
    picture: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    fullname: "Camala Glacken",
    email: "cglackenk@dedecms.com",
    role: "Electrician",
    phoneNumber: "713-121-3431",
    address: "8th Floor",
  },
  {
    picture: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    fullname: "Archibold",
    email: "ageed@liveinternet.ru",
    role: "Project Manager",
    phoneNumber: "943-358-0519",
    address: "Room 486 ",
  },
  {
    picture: "http://dummyimage.com/199x100.png/dddddd/000000",
    fullname: "Mel Peabody",
    email: "mpeabodye@geocities.com",
    role: "Estimator",
    phoneNumber: "768-199-8269",
    address: "Room 822",
  },
  {
    picture: "http://dummyimage.com/118x100.png/ff4444/ffffff",
    fullname: "Micki Tween",
    email: "mtweenf@apache.org",
    role: "Engineer",
    phoneNumber: "778-366-0165",
    address: "Suite 94",
  },
  {
    picture: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    fullname: "Archibold Delort",
    email: "adelortg@cbslocal.com",
    role: "Construction Manager",
    phoneNumber: "842-864-0585",
    address: "17th Floor",
  },
  {
    picture: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    fullname: "Chandra Ciccone",
    email: "ccicconeh@blogs.com",
    role: "Construction Worker",
    phoneNumber: "706-958-0548",
    address: "6th Floor",
  },
  {
    picture: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    fullname: "Hilary Kesten",
    email: "hkesteni@freewebs.com",
    role: "Project Manager",
    phoneNumber: "637-716-9596",
    address: "PO Box 46890",
  },
  {
    picture: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    fullname: "Dani Adolf",
    email: "dadolfj@columbia.edu",
    role: "Estimator",
    phoneNumber: "196-923-9672",
    address: "Room 291",
  },
  {
    picture: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    fullname: "Camala Glacken",
    email: "cglackenk@dedecms.com",
    role: "Electrician",
    phoneNumber: "713-121-3431",
    address: "8th Floor",
  },
  {
    picture: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    fullname: "Archibold",
    email: "ageed@liveinternet.ru",
    role: "Project Manager",
    phoneNumber: "943-358-0519",
    address: "Room 486 ",
  },
  {
    picture: "http://dummyimage.com/199x100.png/dddddd/000000",
    fullname: "Mel Peabody",
    email: "mpeabodye@geocities.com",
    role: "Estimator",
    phoneNumber: "768-199-8269",
    address: "Room 822",
  },
  {
    picture: "http://dummyimage.com/118x100.png/ff4444/ffffff",
    fullname: "Micki Tween",
    email: "mtweenf@apache.org",
    role: "Engineer",
    phoneNumber: "778-366-0165",
    address: "Suite 94",
  },
  {
    picture: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    fullname: "Archibold Delort",
    email: "adelortg@cbslocal.com",
    role: "Construction Manager",
    phoneNumber: "842-864-0585",
    address: "17th Floor",
  },
  {
    picture: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    fullname: "Chandra Ciccone",
    email: "ccicconeh@blogs.com",
    role: "Construction Worker",
    phoneNumber: "706-958-0548",
    address: "6th Floor",
  },
  {
    picture: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    fullname: "Hilary Kesten",
    email: "hkesteni@freewebs.com",
    role: "Project Manager",
    phoneNumber: "637-716-9596",
    address: "PO Box 46890",
  },
  {
    picture: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    fullname: "Dani Adolf",
    email: "dadolfj@columbia.edu",
    role: "Estimator",
    phoneNumber: "196-923-9672",
    address: "Room 291",
  },
  {
    picture: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    fullname: "Camala Glacken",
    email: "cglackenk@dedecms.com",
    role: "Electrician",
    phoneNumber: "713-121-3431",
    address: "8th Floor",
  },
  {
    picture: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    fullname: "Archibold",
    email: "ageed@liveinternet.ru",
    role: "Project Manager",
    phoneNumber: "943-358-0519",
    address: "Room 486 ",
  },
  {
    picture: "http://dummyimage.com/199x100.png/dddddd/000000",
    fullname: "Mel Peabody",
    email: "mpeabodye@geocities.com",
    role: "Estimator",
    phoneNumber: "768-199-8269",
    address: "Room 822",
  },
  {
    picture: "http://dummyimage.com/118x100.png/ff4444/ffffff",
    fullname: "Micki Tween",
    email: "mtweenf@apache.org",
    role: "Engineer",
    phoneNumber: "778-366-0165",
    address: "Suite 94",
  },
  {
    picture: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    fullname: "Archibold Delort",
    email: "adelortg@cbslocal.com",
    role: "Construction Manager",
    phoneNumber: "842-864-0585",
    address: "17th Floor",
  },
  {
    picture: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    fullname: "Chandra Ciccone",
    email: "ccicconeh@blogs.com",
    role: "Construction Worker",
    phoneNumber: "706-958-0548",
    address: "6th Floor",
  },
  {
    picture: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    fullname: "Hilary Kesten",
    email: "hkesteni@freewebs.com",
    role: "Project Manager",
    phoneNumber: "637-716-9596",
    address: "PO Box 46890",
  },
  {
    picture: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    fullname: "Dani Adolf",
    email: "dadolfj@columbia.edu",
    role: "Estimator",
    phoneNumber: "196-923-9672",
    address: "Room 291",
  },
  {
    picture: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    fullname: "Camala Glacken",
    email: "cglackenk@dedecms.com",
    role: "Electrician",
    phoneNumber: "713-121-3431",
    address: "8th Floor",
  },
];
export const roleCodeColor = [
  {
    Employee: "green",
  },
  {
    Manager: "purple",
  },
  {
    Admin: "red",
  },
];

export const leaveRequestDumbData = [
  {
    id: 1,
    fullname: "Filberte Leechman",
    email: "fleechman0@engadget.com",
    role: "Estimator",
    department:
      "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    reason:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    note: "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    startDate: "3/13/2023",
    endDate: "6/20/2022",
    leaveType: "Drywall & Acoustical (FED)",
    isApproved: false,
  },
  {
    id: 2,
    fullname: "Jacquelynn Dionisetti",
    email: "jdionisetti1@scribd.com",
    role: "Project Manager",
    department:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    reason:
      "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    note: "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    startDate: "7/22/2022",
    endDate: "12/21/2022",
    leaveType: "Glass & Glazing",
    isApproved: false,
  },
  {
    id: 3,
    fullname: "Hermine Rouby",
    email: "hrouby2@t-online.de",
    role: "Surveyor",
    department: "Nam tristique tortor eu pede.",
    reason:
      "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
    note: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    startDate: "10/28/2022",
    endDate: "10/29/2022",
    leaveType: "Electrical",
    isApproved: false,
  },
  {
    id: 4,
    fullname: "Kikelia Marieton",
    email: "kmarieton3@vistaprint.com",
    role: "Electrician",
    department: "Sed ante.",
    reason: "Vivamus vel nulla eget eros elementum pellentesque.",
    note: "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.",
    startDate: "11/4/2022",
    endDate: "9/11/2022",
    leaveType: "Prefabricated Aluminum Metal Canopies",
    isApproved: false,
  },
  {
    id: 5,
    fullname: "Lyn Thewys",
    email: "lthewys4@google.pl",
    role: "Estimator",
    department:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    reason:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    note: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",
    startDate: "11/4/2022",
    endDate: "12/23/2022",
    leaveType: "Prefabricated Aluminum Metal Canopies",
    isApproved: true,
  },
  {
    id: 6,
    fullname: "Lazar Baggaley",
    email: "lbaggaley5@biblegateway.com",
    role: "Construction Foreman",
    department:
      "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    reason: "Fusce consequat. Nulla nisl. Nunc nisl.",
    note: "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    startDate: "10/22/2022",
    endDate: "11/9/2022",
    leaveType: "Elevator",
    isApproved: true,
  },
  {
    id: 7,
    fullname: "Flore Baish",
    email: "fbaish6@wiley.com",
    role: "Electrician",
    department: "Nulla nisl. Nunc nisl.",
    reason:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    note: "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    startDate: "6/3/2022",
    endDate: "2/10/2023",
    leaveType: "Overhead Doors",
    isApproved: true,
  },
  {
    id: 8,
    fullname: "Brittaney Sumner",
    email: "bsumner7@webeden.co.uk",
    role: "Estimator",
    department:
      "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    reason:
      "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    note: "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    startDate: "3/14/2023",
    endDate: "1/4/2023",
    leaveType: "Elevator",
    isApproved: true,
  },
  {
    id: 9,
    fullname: "Hermon McGuinley",
    email: "hmcguinley8@tiny.cc",
    role: "Construction Foreman",
    department: "Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
    reason:
      "Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    note: "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    startDate: "9/2/2022",
    endDate: "2/21/2023",
    leaveType: "Waterproofing & Caulking",
    isApproved: false,
  },
  {
    id: 10,
    fullname: "Maia Darbon",
    email: "mdarbon9@icio.us",
    role: "Construction Manager",
    department:
      "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    reason:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    note: "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
    startDate: "8/22/2022",
    endDate: "1/5/2023",
    leaveType: "Sitework & Site Utilities",
    isApproved: true,
  },
  {
    id: 11,
    fullname: "Temp D'Aulby",
    email: "tdaulbya@youku.com",
    role: "Construction Worker",
    department:
      "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
    reason:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    note: "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
    startDate: "9/16/2022",
    endDate: "12/9/2022",
    leaveType: "Painting & Vinyl Wall Covering",
    isApproved: false,
  },
  {
    id: 12,
    fullname: "Fredric McGloughlin",
    email: "fmcgloughlinb@youtube.com",
    role: "Estimator",
    department:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
    reason:
      "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
    note: "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    startDate: "5/9/2022",
    endDate: "7/25/2022",
    leaveType: "Marlite Panels (FED)",
    isApproved: true,
  },
  {
    id: 13,
    fullname: "Massimiliano Nethercott",
    email: "mnethercottc@xing.com",
    role: "Construction Manager",
    department:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    reason:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    note: "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.",
    startDate: "2/12/2023",
    endDate: "8/10/2022",
    leaveType: "Drilled Shafts",
    isApproved: false,
  },
  {
    id: 14,
    fullname: "Dela Kordes",
    email: "dkordesd@delicious.com",
    role: "Surveyor",
    department: "Sed vel enim sit amet nunc viverra dapibus.",
    reason:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    note: "Nunc purus.",
    startDate: "12/6/2022",
    endDate: "12/2/2022",
    leaveType: "Framing (Wood)",
    isApproved: true,
  },
  {
    id: 15,
    fullname: "Porty Mellsop",
    email: "pmellsope@webeden.co.uk",
    role: "Project Manager",
    department:
      "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    reason:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.",
    note: "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    startDate: "9/12/2022",
    endDate: "2/14/2023",
    leaveType: "HVAC",
    isApproved: false,
  },
  {
    id: 16,
    fullname: "Lisetta Flatt",
    email: "lflattf@icio.us",
    role: "Construction Foreman",
    department:
      "Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
    reason:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    note: "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.",
    startDate: "11/22/2022",
    endDate: "1/12/2023",
    leaveType: "Overhead Doors",
    isApproved: true,
  },
  {
    id: 17,
    fullname: "Johann Ghione",
    email: "jghioneg@sohu.com",
    role: "Engineer",
    department:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    reason:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    note: "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.",
    startDate: "7/24/2022",
    endDate: "5/6/2022",
    leaveType: "Framing (Wood)",
    isApproved: false,
  },
  {
    id: 18,
    fullname: "Sarah Haster",
    email: "shasterh@hibu.com",
    role: "Supervisor",
    department:
      "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    reason:
      "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",
    note: "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    startDate: "7/28/2022",
    endDate: "5/19/2022",
    leaveType: "Construction Clean and Final Clean",
    isApproved: true,
  },
  {
    id: 19,
    fullname: "Berrie O'Dogherty",
    email: "bodoghertyi@geocities.jp",
    role: "Subcontractor",
    department:
      "Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
    reason: "Aliquam quis turpis eget elit sodales scelerisque.",
    note: "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    startDate: "4/19/2023",
    endDate: "6/13/2022",
    leaveType: "Construction Clean and Final Clean",
    isApproved: false,
  },
  {
    id: 20,
    fullname: "Gabriele Bellon",
    email: "gbellonj@youtu.be",
    role: "Supervisor",
    department:
      "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    reason:
      "Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
    note: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    startDate: "10/4/2022",
    endDate: "5/22/2022",
    leaveType: "Sitework & Site Utilities",
    isApproved: true,
  },
];
