import { PERMISSION, ROLE } from "../constant/database.constant";

export const application_permission = {
  "account-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
  ],
  "profile-management": [
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.UPDATE}`,
    `${ROLE.MANAGER}-${PERMISSION.DELETE}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.UPDATE}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.DELETE}`,
  ],
  "department-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_PERMISSION}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_POSITION}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
  ],
  "assign-department-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_PERMISSION}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_POSITION}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
  ],
  "organization-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
  ],
  "employee-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_PERMISSION}`,
    `${ROLE.ADMIN}-${PERMISSION.GRANT_POSITION}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
  ],
  "shifttype-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
  ],
  "workshift-management": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.MANAGER}-${PERMISSION.CREATE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.UPDATE}`,
    `${ROLE.MANAGER}-${PERMISSION.DELETE}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
  ],
  "leave-request-personal": [
    `${ROLE.ADMIN}-${PERMISSION.CREATE}`,
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.CREATE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.READ}`,
    `${ROLE.EMPLOYEE}-${PERMISSION.CREATE}`,
  ],
  "leave-request-management": [
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.UPDATE}`,
    `${ROLE.MANAGER}-${PERMISSION.DELETE}`,
  ],
  "attendance-exception-management": [
    `${ROLE.ADMIN}-${PERMISSION.READ}`,
    `${ROLE.ADMIN}-${PERMISSION.UPDATE}`,
    `${ROLE.ADMIN}-${PERMISSION.DELETE}`,
    `${ROLE.MANAGER}-${PERMISSION.READ}`,
    `${ROLE.MANAGER}-${PERMISSION.UPDATE}`,
    `${ROLE.MANAGER}-${PERMISSION.DELETE}`,
  ],
}

export const application_admin_account = [
  {
    fullname: "admin",
    email: "admin@unfame.tech",
    password: "admin123!!!",
    roleName: "admin"
  },
  {
    fullname: "junrante",
    email: "junrante@gmail.com",
    password: "741123963",
    roleName: "admin"
  },
]