version: "3.8"

services:
  mysql:
    image: mysql:8.0.30
    container_name: KLTN_database
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  express:
    image: backend-express
    container_name: KLTN_backend-express
    restart: always
    depends_on:
      - mysql
    build: ./backend
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/abfr

  react:
    image: frontend-react
    container_name: KLTN_frontend-react
    restart: always
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - express

volumes:
  db: